name: resume-app
region: fra

services:
  - name: backend
    github:
      repo: Basartemiz/resume_maker_app
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
      - path: /resume
      - path: /register
      - path: /admin
    envs:
      - key: ALLOWED_HOSTS
        value: resumai.art,www.resumai.art,${APP_DOMAIN}
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: CORS_ALLOWED_ORIGINS
        value: https://resumai.art,https://www.resumai.art

static_sites:
  - name: frontend
    github:
      repo: Basartemiz/resume_maker_app
      branch: main
      deploy_on_push: true
    source_dir: /resume-frontend
    build_command: npm ci && npm run build
    output_dir: dist
    routes:
      - path: /
    catchall_document: index.html
    envs:
      - key: VITE_API_URL
        value: https://resumai.art
